### ISSUE TITLE
Teleport to spawn on join not working as expected

### ISSUE THREAD

**Issue by Themis3000** [rockquiet/Spawn#11]
Hi there! I'm having some troubles configuring this plugin to do what I expect. I'm running a 3 server network. All 3 servers running paper, the "hub" server is the one running this plugin. I'm using Velocity as the proxy for the network.

Here's a relevant snippet of the config file:

```yml
# teleport the player to spawn on join
teleport-on-join:
  enabled: true
  # teleport the player ONLY on first join
  only-first-join: false
```

What I expect to happen: Whenever the player joins the hub, the player is teleported to spawn.

What is actually happening: The player maintains their last position.

I've already restarted the server and such. The /spawn set and /spawn commands are working as intended.

Let me know if there's anything else I'm supposed to do to achieve my goal, or if that goal is something this plugin even aims to solve. Thank you for your time and work on this plugin!
